version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: image-uploader-backend
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:14
    container_name: postgresimageuploader
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-prisma-docker-db
